### ISSUE TITLE
모바일 반응형을 대응한 상세  페이지를 구현한다.

### ISSUE THREAD

**Issue by hwangstar156** [dev-wiki-kr/dev-wiki#18]

**Comment by Zalgritte** [comment]
[Figma - 페이지디자인(mobile](https://www.figma.com/design/0l5I0FwOIVFHTVDiA9dTxG/DevWiki-%EB%94%94%EC%9E%90%EC%9D%B8?node-id=183%3A97&t=ZkuJE34cemE1IOon-1)

시안 참조하시면 되겠습니다!
