### ISSUE TITLE
검색 디자인 추가

### ISSUE THREAD

**Issue by hwangstar156** [dev-wiki-kr/dev-wiki#31]
- 헤더, 메인페이지에 둘다 필요
- 모바일 반응형 고려

**Comment by Zalgritte** [comment]
[Figma - 검색창](https://www.figma.com/design/0l5I0FwOIVFHTVDiA9dTxG/DevWiki-%EB%94%94%EC%9E%90%EC%9D%B8?node-id=278-229&t=ML6PBy5BzUq2EIli-1)
